<a href="https://colab.research.google.com/github/Aleister03/Aleister03/blob/main/CSE220_Fall'24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Array_Learning

In [ ]:
N = int(input())
arr = np.array([0]*N)
for i in range(N):
  user_input = int(input())
  arr[i] = user_input
print(f"Original Array: {arr}")

new_inpt = int(input())
new_arr = np.zeros(N+1, dtype = int)
for i in range(len(arr)):
  new_arr[i] = arr[i]
new_arr[N] = new_inpt
print(f"Resized Array: {new_arr}")

3
4
1
0
Original Array: [4 1 0]
3
Resized Array: [4 1 0 3]


In [ ]:
def converting_into_binary(arr):
  print(f"Original Array: {arr}")
  new_arr = np.zeros(len(arr), dtype = int)
  for i in range(len(arr)):
    if arr[i]>0:
      new_arr[i] = 1
    else:
      new_arr[i] = 0
  print(f"After Modifying: {new_arr}")

arr = np.array([-3, 3, 0, 1, -1], dtype = int)
converting_into_binary(arr)

Original Array: [-3  3  0  1 -1]
After Modifying: [0 1 0 1 0]


In [ ]:
def reverseArray(arr):
  for i in range(len(arr)):
    start=0
    end=len(arr[i])-1
    while start<end:
      arr[i][start], arr[i][end] = arr[i][end], arr[i][start]
      start+=1
      end-=1
  return(arr)

arr = np.array([ [ 4, 3, 8, 6], [ 2, 5, 1, 3], [ 7, -1, 9, 4], [5, 4, -2, 0], [ 5, 7, 1, 3] ])
reversed_arr = reverseArray(arr)
print(reversed_arr)

[[ 6  8  3  4]
 [ 3  1  5  2]
 [ 4  9 -1  7]
 [ 0 -2  4  5]
 [ 3  1  7  5]]


In [ ]:
arr = np.array([ [ 4, 3, 8], [ 2, 5, 1], [ 7, -1, 9], [5, 4, -2] ])
for i in range(len(arr)):
  sum=0
  for j in range(len(arr[i])):
    sum+=arr[i][j]
  print(sum)
print("-----------------------------------------")
for i in range(len(arr)):
  if i%2==0:
    print(arr[i])
  else:
    temp_arr=np.zeros(len(arr[i]), type(int))
    temp=0
    for j in range(len(arr[i])-1, -1, -1):
      temp_arr[temp]=arr[i][j]
      temp+=1
    arr[i]=temp_arr
    print(arr[i])

15
8
15
7
-----------------------------------------
[4 3 8]
[1 5 2]
[ 7 -1  9]
[-2  4  5]


In [ ]:
def sorted(arr):
  print(f"Original Array: {arr}")
  for i in range(len(arr)):
    min_idx=i
    for j in range(i+1, len(arr)):
      if arr[min_idx]>arr[j]:
        min_idx = j
    arr[i], arr[min_idx] = arr[min_idx], arr[i]
  print(f"Sorted Array: {arr}")
arr = np.array([3,1,4,6,2,5])
sorted(arr)

Original Array: [3 1 4 6 2 5]
Sorted Array: [1 2 3 4 5 6]


In [ ]:
def flatten(arr):
  new_arr = np.zeros((len(arr)*len(arr[0])), dtype = int)
  temp=0
  for i in range(len(arr)):
    for j in range(len(arr[i])):
      new_arr[temp] = arr[i][j]
      temp+=1
  return new_arr

arr = np.array( [ [1, 4, 8], [5, 6, 2], [8, 9, 3] ] )
flatten_arr = flatten(arr)
print(flatten_arr)

[1 4 8 5 6 2 8 9 3]


In [ ]:
def dot_proudct(vec1, vec2):
  dot_product=0
  for i in range(len(vec1)):
    dot_product += vec1[i]*vec2[i]
  print(f"Dot Product: {dot_product}")
def swapping_elements(vec1, vec2):
  for i in range(len(vec1)):
    if i%2==0:
      vec1[i], vec2[i] = vec2[i], vec1[i]
    else:
      vec1[i], vec2[i] = vec1[i], vec2[i]
  print(f"Swapped Vector 1: {vec1}")
  print(f"Swapped Vector 2: {vec2}")
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
dot_proudct(vec1, vec2)
swapping_elements(vec1, vec2)

Dot Product: 32
Swapped Vector 1: [4 2 6]
Swapped Vector 2: [1 5 3]


In [ ]:
def sorting_positive_negative(arr):
  new_arr = np.array(([0]*len(arr)), dtype=int)
  temp=0
  for i in range(len(arr)):
    if arr[i]>0:
      new_arr[temp]=arr[i]
      temp+=1
  for i in range(len(arr)):
    if arr[i]<0:
      new_arr[temp]=arr[i]
      temp+=1
  print(new_arr)
arr1 = np.array([1, -1, 3, 2, -7, -5, 11, 6], dtype=int)
sorting_positive_negative(arr1)
arr2 = np.array([-5, 7, -3, -4, 9, 10, -1, 11], dtype=int)
sorting_positive_negative(arr2)

[ 1  3  2 11  6 -1 -7 -5]
[ 7  9 10 11 -5 -3 -4 -1]


In [ ]:
def is_identity_matrix(matrix):
  n = len(matrix)
  for i in range(n):
    for j in range(n):
      if i == j:
        if matrix[i][j] != 1:
          print("Not an Identity matrix")
          return
      else:
        if matrix[i][j] != 0:
          print("Not an Identity matrix")
          return
  print("Identity matrix")

A = np.array([ [1, 0, 0, 0, 0],
               [0, 1, 0, 0, 0],
               [0, 0, 1, 0, 0],
               [0, 0, 0, 1, 0],
               [0, 0, 0, 0, 1]])
is_identity_matrix(A)
B = np.array([ [1, 0, 0],
               [0, 1, 0],
               [0, 0, 2] ])
is_identity_matrix(B)

Identity matrix
Not an Identity matrix


In [ ]:
def difference(arr):
  n=len(arr)
  sum_main=sum_sec=0
  for i in range(n):
    sum_main+=arr[i][i]
  start=0
  for j in range(n-1, -1, -1):
    sum_sec+=arr[start][j]
    start+=1
  return abs(sum_main-sum_sec)

A = np.array([ [1, 5, 12, 1],
               [2, -4, 6, 7],
               [3,  8,  5,  9],
               [3, 5, 23, -6] ])
print("Difference:", difference(A))

Difference: 22


In [ ]:
def transpose(M1):
  M2 = np.zeros((len(M1[0]), len(M1)), dtype = int)
  for i in range(len(M1)):
    for j in range(len(M1[i])):
      M2[j][i] = M1[i][j]
  return M2

def gram_matrix(M1,M2):
  if len(M1[0])==len(M2):
    M3 = np.zeros((len(M1), len(M2[0])), dtype = int)
    for i in range(len(M2)):
      for j in range(len(M1)):
        for k in range(len(M3)):
          M3[k][j] += M1[j][i] * M2[i][k]
  return M3

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B=transpose(A)
print(B)
C=gram_matrix(B,A)
print(C)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [ ]:
def leftshift(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  return arr
arr=np.array([10,20,30,40,50])
print(leftshift(arr))

[20 30 40 50  0]


In [ ]:
def rightshift(arr):
  for i in range(len(arr)-2, -1, -1):
    arr[i+1] = arr[i]
  arr[0] = 0
  return arr
arr=np.array([10,20,30,40,50])
print(rightshift(arr))

[ 0 10 20 30 40]


In [ ]:
A = np.array([ [1, 5, 12, 1],
               [2, -4, 6, 7],
               [3,  8,  5,  9],
               [3, 5, 23, -6] ])
print(f"Before: \n{A}")
for i in range(len(A)):
  for j in range(len(A[i])):
    if (i+1)<len(A) and (i-1)!=-1 and (j+1)<len(A[i]) and (j-1)!=-1:
      A[i][j] = A[i][j] + A[i-1][j] + A[i+1][j] + A[i][j-1] + A[i][j+1]
    elif (i-1)<0 and (i+1)<len(A) and (j+1)<len(A[i]) and (j-1)!=-1:
      A[i][j] = A[i][j] + 0 + A[i+1][j] + A[i][j-1] + A[i][j+1]
    elif (i+1)<len(A) and (i-1)<0 and (j+1)>=len(A[i]) and (j-1)!=-1:
      A[i][j] = A[i][j] + 0 + A[i+1][j] + A[i][j-1] + 0
    elif (j+1)>=len(A[i]) and (j-1)!=-1 and (i+1)<len(A) and (i-1)!=-1:
      A[i][j] = A[i][j] + A[i-1][j] + A[i+1][j] + A[i][j-1] + 0
    elif (i-1)<0 and (i+1)<len(A) and (j-1)<0 and (j+1)<len(A[i]):
      A[i][j] = A[i][j] + 0 + A[i+1][j] + 0 + A[i][j+1]
    elif (i+1)<len(A) and (i-1)!=-1 and (j+1)<len(A[i]) and (j-1)<0:
      A[i][j] = A[i][j] + A[i-1][j] + A[i+1][j] + 0 + A[i][j+1]
    elif (i-1)!=-1 and (i+1)>=len(A) and (j+1)<len(A[i]) and (j-1)!=-1:
      A[i][j] = A[i][j] + A[i-1][j] + 0 + A[i][j-1] + A[i][j+1]
    elif (i-1)!=-1 and (i+1)>=len(A) and (j+1)<len(A[i]) and (j-1)<0:
      A[i][j] = A[i][j] + A[i-1][j] + 0 + 0 + A[i][j+1]
    elif (i+1)>=len(A) and (i-1)!=-1 and (j+1)>=len(A[i]) and (j-1)!=-1:
      A[i][j] = A[i][j] + A[i-1][j] + 0 + A[i][j-1] + 0
print(f"After: \n{A}")

Before: 
[[ 1  5 12  1]
 [ 2 -4  6  7]
 [ 3  8  5  9]
 [ 3  5 23 -6]]
After: 
[[  8  21  40  48]
 [  9  40  98 162]
 [ 23  81 216 381]
 [ 31 140 373 748]]


In [ ]:
def multiplication_of_matrices(M1, M2):
  if len(M1[0])==len(M2):
    M3 = np.zeros((len(M1), len(M2[0])), dtype=int)
    for i in range(len(M1[0])):
      for j in range(len(M1)):
        for k in range(len(M3[j])):
          M3[j][k] += M1[j][i]*M2[i][k]
  else:
    M3 = "Multiplication not possible"
  return M3
M1 = np.array([[1, 3, 4],
              [3, 2, 1],
              [-2, 6, 2],
              [8, 4, 3]])
M2 = np.array([[4, 5],
              [-3, 2],
              [3, 8]])
print(multiplication_of_matrices(M1, M2))

[[  7  43]
 [  9  27]
 [-20  18]
 [ 29  72]]


In [ ]:
def printPairs(arr, sum):
  found=False
  for i in range(len(arr)):
    for j in range(i+1, len(arr)):
      if arr[i]+arr[j]==sum:
        print(arr[i], arr[j])
        found=True
  if found==False:
    print("No Pair Found")

arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)

7 8
10 5


#Lab-01

In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

In [ ]:
#Task 01: Merge Lineup

def mergeLineup(pokemon_1, pokemon_2):
  temp = 0
  new_arr = np.zeros(len(pokemon_1), dtype=int)
  for i in range(len(pokemon_2)-1, -1, -1):
    if pokemon_2[i] == None and pokemon_1[temp] != None:
      new_arr[temp] += pokemon_1[temp]
    elif pokemon_2[i] != None and pokemon_1[temp] == None:
      new_arr[temp] += pokemon_2[i]
    elif pokemon_1[temp] == None and pokemon_2[i] == None:
      new_arr[temp] += 0
    else:
      new_arr[temp] += pokemon_1[temp]+pokemon_2[i]
    temp+=1
  return new_arr

print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))
pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Task 01: Merge Lineup  ///
Task 1: [12  3 28 -8  5]
Accepted
Task 1: [ 4 17  6 27  2]
Accepted


In [ ]:
# Task 02: Discard Cards

def discardCards(cards, t):
  count = 0
  new_arr = np.zeros((len(cards)), dtype = int)
  for i in range(len(cards)):
    if cards[i] == t:
      count+=1
      if count%2 != 0:
        cards[i] =0

  temp=0
  for i in range(len(cards)):
    if cards[i] != 0:
      new_arr[temp] = cards[i]
      temp+=1

  return new_arr

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

///  Task 02: Discard Cards  ///
Task 2: [1 3 7 5 2 2 0 0 0]
Accepted
Task 2: [5 0 0 0 0]
Accepted


In [ ]:
#Task 03: Decryption Process

def decrypt_matrix(matrix):
  new_arr=np.zeros(len(matrix[0])-1, dtype=int)
  sum_col1=sum_col2=sum_col3=0
  for i in range(len(matrix)):
    sum_col1 += matrix[i][0]
    sum_col2 += matrix[i][1]
    sum_col3 += matrix[i][2]
  new_arr[0]=sum_col2-sum_col1
  new_arr[1]=sum_col3-sum_col2
  return new_arr

matrix=np.array([[1,3,1],
                 [6,4,2],
                 [5,1,7],
                 [9,3,3],
                 [8,5,4]
                 ])

returned_array=decrypt_matrix(matrix)
print(returned_array)
#This should print [-13, 1]

[-13   1]


In [ ]:
# Task 04: Zigzag Walk

def walk_zigzag(floor):
  row,col = floor.shape
  for i in range(col):
    temp=""
    if i%2==0:
      for j in range(row):
        if j%2==0:
          temp+=floor[j][i]+" "
      print(temp)
    else:
      for j in range(row-1, -1, -1):
        if j%2!=0:
          temp+=floor[j][i]+" "
      print(temp)

floor = np.array([['3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


In [ ]:
# Task 05: Row Rotation Policy of BRACU Classroom
def row_rotation(exam_week, seat_status):
  for n in range(exam_week-1):
    temp=np.array(seat_status[len(seat_status)-1])
    for i in range(len(seat_status)-2, -1, -1):
      seat_status[i+1]=seat_status[i]
    seat_status[0]=temp
  print_matrix(seat_status)
  for i in range(len(seat_status)):
    for j in range(len(seat_status[i])):
      if seat_status[i][j]=="AA":
        row_number=i+1
  return row_number
seat_status = np.array([['A' , 'B' , 'C' , 'D' , 'E'],
                        ['F' , 'G' , 'H' , 'I' , 'J'],
                        ['K' , 'L' , 'M' , 'N' , 'O'],
                        ['P' , 'Q' , 'R' , 'S' , 'T'],
                        ['U' , 'V' , 'W' , 'X' , 'Y'],
                        ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------
|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
Your friend AA will be on row 2


In [ ]:
#Task 06: Matrix Compression

def compress_matrix(mat):
  row,col=matrix.shape
  new_Arr = np.zeros((int(row/2), int(col/2)), dtype=int)
  for i in range(0, row, 2):
    for j in range(0, col, 2):
      new_Arr[i//2][j//2]=matrix[i][j]+matrix[i][j+1]+matrix[i+1][j]+matrix[i+1][j+1]
  return new_Arr
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print("...............")
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print

#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

|  1  |  2  |  3  |  4  |
-------------------------
|  5  |  6  |  7  |  8  |
-------------------------
|  1  |  3  |  5  |  2  |
-------------------------
|  -2 |  0  |  6  |  -3 |
-------------------------
...............
|  14 |  22 |
-------------
|  2  |  10 |
-------------


In [ ]:
#Task 07: Game Arena

def play_game(arena):
  team_points = 0
  for i in range(len(arena)):
    for j in range(len(arena[i])):
      if arena[i][j] >= 50 and arena[i][j] % 2 == 0:
        if i+1<len(arena) and arena[i+1][j]==2:
          team_points+=2
        if i-1>=0 and arena[i-1][j]==2:
          team_points+=2
        if j+1<len(arena[i]) and arena[i][j+1]==2:
          team_points+=2
        if j-1>=0 and arena[i][j-1]==2:
          team_points+=2
  print(f"Points Gained: {team_points}.", end=" ")
  print(f"Your team is out." if (team_points) < 10 else "Your team has survived the game.")
arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

|  0  |  2  |  2  |  0  |
-------------------------
|  50 |  1  |  2  |  0  |
-------------------------
|  2  |  2  |  2  |  0  |
-------------------------
|  1  |  100 |  2  |  0  |
-------------------------
Points Gained: 6. Your team is out.
.....................
|  0  |  2  |  2  |  0  |  2  |
-------------------------------
|  1  |  50 |  2  |  1  |  100 |
-------------------------------
|  2  |  2  |  2  |  0  |  2  |
-------------------------------
|  0  |  200 |  2  |  0  |  0  |
-------------------------------
Points Gained: 14. Your team has survived the game.
